# Linear Algebra with NUMPY

In [14]:
import numpy as np

In [ ]:
#DOT PRODUCT 
np.random.seed(10)
a=np.random.randint(1,11,size=(4))                   
b=np.random.randint(1,11,size=(4))
print(a,b)

dot_product=np.dot(a,b)
print(dot_product)


In [16]:
#MATRIX MULTIPLICATION

a=np.random.randint(1,11,size=(4,4))                   
b=np.random.randint(1,11,size=(4,6))
print(a,b)
mat_mul=np.matmul(a,b)
mat_mul1=np.dot(a,b)

print(mat_mul==mat_mul1)
print(mat_mul)

# print(mat_mul1)

[[ 6 10  1  2]
 [ 1  2 10  1]
 [10  3  2  2]
 [ 1  1  6 10]] [[ 1  5  7  7  1  3]
 [ 4  4  3  7  1  6]
 [ 2  4  7  6  6  2]
 [ 9  1  6 10  9  6]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[ 66  76  91 138  40  92]
 [ 38  54  89  91  72  41]
 [ 44  72 105 123  43  64]
 [107  43 112 150 128  81]]
