# Linear Algebra with NUMPY

In [ ]:
import numpy as np

In [ ]:
#DOT PRODUCT 
np.random.seed(10)
a=np.random.randint(1,11,size=(4))                   
b=np.random.randint(1,11,size=(4))
print(a,b)

dot_product=np.dot(a,b)
print(dot_product)


In [ ]:
#MATRIX MULTIPLICATION

a=np.random.randint(1,11,size=(4,4))                   
b=np.random.randint(1,11,size=(4,6))
print(a,b)
mat_mul=np.matmul(a,b)
mat_mul1=np.dot(a,b)

print(mat_mul==mat_mul1)
print(mat_mul)

# print(mat_mul1)

### Finding the Detereminant, Transpose and Inverse 


In [ ]:
import numpy as np
np.random.seed(4)
A=np.random.randint(1,11,size=(4,4))
determinant=np.linalg.det(A)
print(determinant)
print("-"*20)
Transpose=np.transpose(A)
print(Transpose)
print("-"*20)

Inverse=np.linalg.inv(A)
print(Inverse)

## SYSTEM OF LINEAR EQUATION

In [1]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10],[11],[12]])
print("DET A",np.linalg.det(A))
sol=np.linalg.solve(A,B)
print(sol)

cofactors = np.zeros(A.shape)
    
    # Iterate through each element in the matrix
for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            # Create the submatrix by removing the i-th row and j-th column
            submatrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
            
            # Calculate the minor (determinant of the submatrix)
            minor = np.linalg.det(submatrix)
            
            # Apply the sign based on position and assign to the cofactor matrix
            cofactors[i, j] = ((-1) ** (i + j)) * minor
    
print(np.matmul(cofactors,B))

DET A -9.51619735392994e-16
[[  2.26666667]
 [-13.53333333]
 [ 11.6       ]]
[[0.00000000e+00]
 [0.00000000e+00]
 [1.42108547e-14]]


In [ ]:
A=np.array([[3,11],[6,22]])
B=np.array([[7],[5]])
print("DET A",np.linalg.det(A))
sol=np.linalg.solve(A,B)
print(sol)

cofactors = np.zeros(A.shape)
    
    # Iterate through each element in the matrix
for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            # Create the submatrix by removing the i-th row and j-th column
            submatrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
            
            # Calculate the minor (determinant of the submatrix)
            minor = np.linalg.det(submatrix)
            
            # Apply the sign based on position and assign to the cofactor matrix
            cofactors[i, j] = ((-1) ** (i + j)) * minor
    
print(np.matmul(cofactors,B))

In [ ]:
A=np.array([[3,2,7],[4,-3,2],[5,9,23]])
print(A)
B=np.array([[0],[0],[0]])
print("DET A",np.linalg.det(A))
sol=np.linalg.solve(A,B)
print(sol)

cofactors = np.zeros(A.shape)
    
    # Iterate through each element in the matrix
for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            # Create the submatrix by removing the i-th row and j-th column
            submatrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
            
            # Calculate the minor (determinant of the submatrix)
            minor = np.linalg.det(submatrix)
            
            # Apply the sign based on position and assign to the cofactor matrix
            cofactors[i, j] = ((-1) ** (i + j)) * minor
    
print(np.matmul(cofactors,B))

In [ ]:
A=np.array([[3,2,7],[6,4,14],[5,9,23]])
print(A)
B=np.array([[0],[0],[0]])
print("DET A",np.linalg.det(A))

### EIGEN VALUES AND EIGEN VECTORS

In [2]:
A=np.array([[2,3,5],[3,4,7],[8,6,4]])
print(A)

eigen_val,eigen_vec=np.linalg.eig(A)

print(eigen_val)
print(eigen_vec)

[[2 3 5]
 [3 4 7]
 [8 6 4]]
[14.20348047 -0.17475834 -4.02872213]
[[-0.42572905 -0.47018582 -0.37125082]
 [-0.59365607  0.83192961 -0.52750832]
 [-0.68288157 -0.29464966  0.7641386 ]]


In [3]:
A=np.array([[5,4],[1,2]])
print(A)

eigen_val,eigen_vec=np.linalg.eig(A)

print(eigen_val)
print(4*eigen_vec)

[[5 4]
 [1 2]]
[6. 1.]
[[ 3.88057    -2.82842712]
 [ 0.9701425   2.82842712]]
