In [2]:
import numpy as np
arr=np.random.randint(1,30,size=(5,5))

# Filtering 

1. filter all the elements which are divisible by 5

In [4]:
print(arr)
print(arr%5==0)
print(arr[arr%5==0])

[[ 4 10  5 25 11]
 [18 15 17 22  1]
 [25 12 10  7 28]
 [28 20 23 20 27]
 [14 19 22 19  7]]
[[False  True  True  True False]
 [False  True False False False]
 [ True False  True False False]
 [False  True False  True False]
 [False False False False False]]
[10  5 25 15 25 10 20 20]


2. filter all the elements which are even

In [6]:
print(arr)
print(arr%2==0)
print(arr[arr%2==0])

[[ 4 10  5 25 11]
 [18 15 17 22  1]
 [25 12 10  7 28]
 [28 20 23 20 27]
 [14 19 22 19  7]]
[[ True  True False False False]
 [ True False False  True False]
 [False  True  True False  True]
 [ True  True False  True False]
 [ True False  True False False]]
[ 4 10 18 22 12 10 28 28 20 20 14 22]


3. filter all the elements which are even and divisble by 5

In [11]:
print(arr)
# print((arr%2==0 and arr%5==0))
print(arr[(arr%2==0)& (arr%5==0)])

[[ 4 10  5 25 11]
 [18 15 17 22  1]
 [25 12 10  7 28]
 [28 20 23 20 27]
 [14 19 22 19  7]]
[10 10 20 20]


4. filter all the elements which are divible by either 3 or 7

In [12]:
print(arr[(arr%3==0)| (arr%7==0)])

[18 15 12  7 28 28 27 14  7]


5. Filter array based on condition of another array

In [21]:
cond=np.array([True,False,True,False,False])

print(arr[cond])
print(arr[3][cond])

[[ 4 10  5 25 11]
 [25 12 10  7 28]]
[28 23]


6. Filter array based on any row of array

In [ ]:
print(arr[2,:]>15)
print(arr[arr[2,:]>15])
print(arr[3][arr[2,:]>15])

# Aggregating 

1. sum

In [23]:
arr1=np.array([1,2,3,4,5,6,7])
print(np.sum(arr1))

arr2=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr2))

print(np.sum(arr2,axis=0))
print(np.sum(arr2,axis=1))

28
21
[5 7 9]
[ 6 15]


2. mean

In [25]:
arr1=np.array([1,2,3,4,5,6,7])
print(np.mean(arr1))

arr2=np.array([[1,2,3],[4,5,6]])
print(np.mean(arr2))

print(np.mean(arr2,axis=0))
print(np.mean(arr2,axis=1))

4.0
3.5
[2.5 3.5 4.5]
[2. 5.]


3. standard deviation

In [26]:
arr1=np.array([1,2,3,4,5,6,7])
print(np.std(arr1))

arr2=np.array([[1,2,3],[4,5,6]])
print(np.std(arr2))

print(np.std(arr2,axis=0))
print(np.std(arr2,axis=1))

2.0
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


4. min max

In [24]:
arr1=np.array([1,2,3,4,5,6,7])
print(np.min(arr1))

arr2=np.array([[1,2,3],[4,5,6]])
print(np.min(arr2))

print(np.min(arr2,axis=0))
print(np.min(arr2,axis=1))

print("Max function")
arr1=np.array([1,2,3,4,5,6,7])
print(np.max(arr1))

arr2=np.array([[1,2,3],[4,5,6]])
print(np.max(arr2))

print(np.min(arr2,axis=0))
print(np.max(arr2,axis=1))

1
1
[1 2 3]
[1 4]
7
6
[1 2 3]
[3 6]
