# Searching using NUMPY 

In [1]:
import numpy as np
arr=np.array([2,4,3,6,2,5,7,8,8,43,22,5,7,8,53,3,6,7])

# linearSeach
index=np.where(arr==2)

print(index[0])

#Binary Search

arr=np.sort(arr)
print(arr)
index=np.searchsorted(arr,8,side='right')
print(index)

print(np.argmin(abs(arr-11)))

[0 4]
[ 2  2  3  3  4  5  5  6  6  7  7  7  8  8  8 22 43 53]
15
12


# Sorting

In [27]:
arr=np.array([2,4,3,6,2,5,7,8,8,43,22,5,7,8,53,3,6,7])
print(np.sort(arr,kind="heapsort"))
print(np.sort(arr,kind="quicksort"))
print(np.sort(arr,kind='mergesort'))

[ 2  2  3  3  4  5  5  6  6  7  7  7  8  8  8 22 43 53]
[ 2  2  3  3  4  5  5  6  6  7  7  7  8  8  8 22 43 53]
[ 2  2  3  3  4  5  5  6  6  7  7  7  8  8  8 22 43 53]
