# Converting the Data Structure to the Numpy Array

#### 1. list ot Array

In [2]:
import numpy as np #type: ignore

new_list=list(range(5))
print(new_list)

arr=np.array(new_list)
print(arr)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


#### 2. set to Array

In [3]:
s={5,6,7,8}
print(s)
print(type(s))

print(type(np.array(s)))

{8, 5, 6, 7}
<class 'set'>
<class 'numpy.ndarray'>


#### 3. Dictionary to Array

In [4]:
dict={1:3,4:6,7:8}

k=np.array(list(dict.keys()))
v=np.array(list(dict.values()))

print(k,v)

[1 4 7] [3 6 8]


#### 4. tuple to Array

In [16]:
tup=(5,6,7,8)
print(np.array(list(tup)))

[5 6 7 8]


#### convereting string to array

In [17]:

arr = np.array(list('hello world'))
print(arr)
print(type(arr))

['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


# Converting the type of data of one array to other data type

#### int

In [18]:
arr = np.array([1,2,3,4,5])
print(arr)
arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


#### Float

In [19]:
arr = np.array([1.0,2.0,3.0,4.0,5.0])
print(arr)
arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)


[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


#### Boolean

In [20]:
import numpy as np #type: ignore
arr = np.array([True,True,False,False])
print(arr)
arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('int')
print(arr_)


[ True  True False False]
[1. 1. 0. 0.]
['True' 'True' 'False' 'False']
[1 1 0 0]


#### String

In [21]:
arr = np.array(["1","2","3","4","5"])
print(arr)
arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)


['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[ True  True  True  True  True]
