## FIXED SIZE ARRAYS

#### 1. zero()

In [ ]:
import numpy as np

zero_array=np.zeros(6)
print(zero_array)

zero_array=np.zeros(6,dtype=int)
print(zero_array)

zero_array=np.zeros(6,dtype=str)
print(zero_array)
zero_array=np.zeros(6,dtype=bool)
print(zero_array)
zero_array=np.zeros((6,6),dtype=int)
print(zero_array)
zero_array=np.zeros((2,5,6),dtype=float)
print(zero_array)



#### 2.ones

In [ ]:
ones_array=np.ones(3)
print(ones_array)
ones_array=np.ones(3,dtype=str)
print(ones_array)
ones_array=np.ones((3,5),dtype=int)
print(ones_array)
ones_array=np.ones((3,6,3),dtype=str)
print(ones_array)
ones_array=np.ones(3,dtype=str)
print(ones_array)



#### 3. eye

In [ ]:
eye_array=np.eye(4)
print(eye_array)
print('-'*20)
eye_array=np.eye(3,4)
print(eye_array)
print('-'*20)
print('-'*20)

# print('-'*20)

eye_array=np.eye(4,3,dtype=bool)
print(eye_array)

#### 4. Random

In [ ]:
print(np.random.rand())
print('-'*20)
print(np.random.rand(4))
print('-'*20)
print(np.random.rand(3,3))
print('-'*20)
print(np.random.rand(3,4))
print('-'*20)
# randint(low=,high=,size=)
print(np.random.randint(400))
print('-'*20)
print(np.random.randint(100,size=(4,4)))
print('-'*20)
print(np.random.randint(low=100,high=500,size=(2,4,4)))
print('-'*20)

#randn
print(np.random.randn(5))
print('-'*20)
print(np.random.randn(3,4))
print('-'*20)
print(np.random.randn(4))
print('-'*20)

mean=3
st_dev=5
value=mean+st_dev*np.random.rand(4)
print(value)
print('-'*20)

#### Distributions in random

In [ ]:
print(np.random.uniform(size=(3, 3)))
print('-'*20)
print(np.random.binomial(10, 0.5, size=(3, 3)))

print('-'*20)

print("poisson")
# Parameters:
lam = 5  # Rate parameter (average number of events)

# Generate random numbers from a Poisson distribution
poisson_samples = np.random.poisson(lam, size=10)
print(poisson_samples)
print('-'*20)

print("exponential")
scale = 1/lam  # Scale parameter (inverse of rate)

# Generate random numbers from an exponential distribution
exponential_samples = np.random.exponential(scale, size=10)
print(exponential_samples)
print('-'*20)
print("Gamma")
shape = 2  # Shape parameter (alpha)
scale = 2  # Scale parameter (beta)

# Generate random numbers from a gamma distribution
gamma_samples = np.random.gamma(shape, scale, size=10)
print(gamma_samples)
print('-'*20)
print("chisquare")
# Parameters:
df = 5  # Degrees of freedom

# Generate random numbers from a chi-squared distribution
chi_squared_samples = np.random.chisquare(df, size=10)
print(chi_squared_samples)
print('-'*20)
# Parameters:
print("standard_t")
df = 10  # Degrees of freedom

# Generate random numbers from a t-distribution
t_samples = np.random.standard_t(df, size=10)
print(t_samples)
print('-'*20)
# Parameters:
print("f")
num_df = 5  # Numerator degrees of freedom
denom_df = 10  # Denominator degrees of freedom

# Generate random numbers from an F-distribution
f_samples = np.random.f(num_df, denom_df, size=10)
print(f_samples)

print('-'*20)
print("beta")
# Parameters:
a = 2  # Alpha parameter
b = 3  # Beta parameter

# Generate random numbers from a beta distribution
beta_samples = np.random.beta(a, b, size=10)
print(beta_samples)
print('-'*20)
print("lognormal")
# Parameters:
mean = 0  # Mean of the underlying normal distribution
std = 1  # Standard deviation of the underlying normal distribution

# Generate random numbers from a log-normal distribution
lognormal_samples = np.random.lognormal(mean, std, size=10)
print(lognormal_samples)
print('-'*20)
# Parameters:
print("laplace")
loc = 0  # Location parameter (mean)
scale = 1  # Scale parameter

# Generate random numbers from a Laplace distribution
laplace_samples = np.random.laplace(loc, scale, size=10)
print(laplace_samples)
print('-'*20)




In [1]:
import numpy as np

# Poisson distribution
# lam: expected number of events (λ)
# size: output shape
print("Poisson Distribution:")
print(np.random.poisson(lam=5, size=10))  # 1D array of 10 samples
print(np.random.poisson(lam=5, size=(3, 3)))  # 3x3 2D array

# Exponential distribution
# scale: inverse of the rate parameter (λ), which is 1/λ
# size: output shape
print("\nExponential Distribution:")
print(np.random.exponential(scale=1.0, size=10))  # 1D array of 10 samples
print(np.random.exponential(scale=1.0, size=(3, 3)))  # 3x3 2D array

# Gamma distribution
# shape: shape parameter (k)
# scale: inverse of the rate parameter (θ), which is 1/θ
# size: output shape
print("\nGamma Distribution:")
print(np.random.gamma(shape=2.0, scale=2.0, size=10))  # 1D array of 10 samples
print(np.random.gamma(shape=2.0, scale=2.0, size=(3, 3)))  # 3x3 2D array

# Chi-squared distribution
# df: degrees of freedom
# size: output shape
print("\nChi-squared Distribution:")
print(np.random.chisquare(df=2, size=10))  # 1D array of 10 samples
print(np.random.chisquare(df=2, size=(3, 3)))  # 3x3 2D array

# T-distribution (Student's t-distribution)
# df: degrees of freedom
# size: output shape
print("\nT-distribution:")
print(np.random.standard_t(df=10, size=10))  # 1D array of 10 samples
print(np.random.standard_t(df=10, size=(3, 3)))  # 3x3 2D array

# F-distribution
# dfnum: degrees of freedom in the numerator
# dfden: degrees of freedom in the denominator
# size: output shape
print("\nF-distribution:")
print(np.random.f(dfnum=5, dfden=2, size=10))  # 1D array of 10 samples
print(np.random.f(dfnum=5, dfden=2, size=(3, 3)))  # 3x3 2D array

# Beta distribution
# a: alpha (α) parameter (first shape parameter)
# b: beta (β) parameter (second shape parameter)
# size: output shape
print("\nBeta Distribution:")
print(np.random.beta(a=2.0, b=5.0, size=10))  # 1D array of 10 samples
print(np.random.beta(a=2.0, b=5.0, size=(3, 3)))  # 3x3 2D array

# Log-normal distribution
# mean: mean of the underlying normal distribution
# sigma: standard deviation of the underlying normal distribution
# size: output shape
print("\nLog-normal Distribution:")
print(np.random.lognormal(mean=0.0, sigma=1.0, size=10))  # 1D array of 10 samples
print(np.random.lognormal(mean=0.0, sigma=1.0, size=(3, 3)))  # 3x3 2D array

# Laplace distribution
# loc: location parameter (mean)
# scale: scale parameter (exponential decay)
# size: output shape
print("\nLaplace Distribution:")
print(np.random.laplace(loc=0.0, scale=1.0, size=10))  # 1D array of 10 samples
print(np.random.laplace(loc=0.0, scale=1.0, size=(3, 3)))  # 3x3 2D array


Poisson Distribution:
[ 6  3 10  8 11  6  6  3  4  5]
[[7 6 2]
 [2 6 7]
 [5 3 7]]

Exponential Distribution:
[0.29218158 0.21957986 2.82662483 0.90094518 0.20812038 1.99081676
 1.02951357 0.18198613 0.346831   0.32414967]
[[1.01443022 0.2479506  0.22426041]
 [0.26018774 0.43666538 0.26902754]
 [0.11559354 0.32529778 0.76752687]]

Gamma Distribution:
[ 1.10343803  2.694118   11.57537556  3.73328133  2.8647054   2.1520949
  6.90259087  3.2295422   1.95369205  5.39654872]
[[5.52398014 0.28560921 0.26697679]
 [0.74201056 6.32090211 1.26047235]
 [0.81331239 4.89364571 2.33456926]]

Chi-squared Distribution:
[0.04254719 0.54968075 1.08236484 1.89378314 3.49255261 0.19064172
 0.65815826 1.64857965 2.27839588 0.3485683 ]
[[0.21690254 6.4032963  2.15940159]
 [8.21335472 0.2751934  2.36545837]
 [0.83484268 1.58761506 3.20666133]]

T-distribution:
[-0.69584129  0.48260322  1.23826006  0.49722301  0.09465718 -0.62531002
 -0.39092908  3.41501816 -0.16250073  1.12409284]
[[ 0.86297415 -2.5146673  -1

#### managing randomness using seed

In [ ]:

for i in range(10):
    np.random.seed(6)
    arr=np.random.randint(2,size=(100))
    print(len(arr[arr==1]),len(arr[arr==0]))