# Array Operations

#### 1. range()

In [1]:
print(range(5))
print(list(range(5)))
print(range(4,90))
print(list(range(5,50,5)))

range(0, 5)
[0, 1, 2, 3, 4]
range(4, 90)
[5, 10, 15, 20, 25, 30, 35, 40, 45]


#### 2. np.arange()

In [2]:
import numpy as np

np_array=np.arange(3,6,1.5)
print(np_array)
np_array=np.arange(10,0,-2)
print(np_array)

[3.  4.5]
[10  8  6  4  2]


#### 3. linspace()

In [9]:
l=np.linspace(1,3,6)
print(l)
l=np.linspace(1,3,6,endpoint=False)
print(l)
l,s=np.linspace(1,3,6,retstep=True)
print(l,s)

[1.  1.4 1.8 2.2 2.6 3. ]
[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667]
[1.  1.4 1.8 2.2 2.6 3. ] 0.4


#### 4. logspace()

In [15]:
ls=np.logspace(1,3,8)
print(ls)
ls=np.logspace(1,3,8,base=2,)
print(ls)
arr = np.logspace(0,10,5, base = 2)
print(arr)


[  10.           19.30697729   37.2759372    71.9685673   138.94954944
  268.26957953  517.94746792 1000.        ]
[2.         2.43802731 2.97198858 3.62289466 4.41635805 5.38360077
 6.56268285 8.        ]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


# Manipulating Arrays

## 1. Flattening

In [18]:
np_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_array)
flat_arr=np_array.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


## 2. Reshaping

In [20]:
reshaped=np.reshape(np_array,(9,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## 3. Splitting

- vsplit

In [31]:
np_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
vspl=np.vsplit(np_array,3)
print(vspl)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


- hsplit

In [33]:
hspl=np.hsplit(np_array,3)
print(hspl)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


- split

In [37]:
vspl=np.split(np_array,3,axis=0)
print(vspl)
hspl=np.split(np_array,3,axis=1)
print(hspl)

for _ in hspl:
    print(_)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


## 4. Merging

- concatinate

In [45]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([[22,34,53],[33,64,75]])
arr4=np.array([[25,38,57],[56,65,73]])

concat_arr=np.concatenate((arr1,arr2,arr3,arr4),axis=0)
print(concat_arr)
concat_arr=np.concatenate((arr1,arr2,arr3,arr4),axis=1)
print(concat_arr.shape)
print(concat_arr)

[[ 2  3  5]
 [ 5  6  7]
 [22 33 54]
 [15 26 37]
 [22 34 53]
 [33 64 75]
 [25 38 57]
 [56 65 73]]
(2, 12)
[[ 2  3  5 22 33 54 22 34 53 25 38 57]
 [ 5  6  7 15 26 37 33 64 75 56 65 73]]


- vstack

In [40]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([[22,34,53],[33,64,75]])
arr4=np.array([[25,38,57],[56,65,73]])

vstk=np.vstack((arr1,arr2,arr3,arr4))
print(vstk)

[[ 2  3  5]
 [ 5  6  7]
 [22 33 54]
 [15 26 37]
 [22 34 53]
 [33 64 75]
 [25 38 57]
 [56 65 73]]


- hstack

In [43]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([[22,34,53],[33,64,75]])
arr4=np.array([[25,38,57],[56,65,73]])

hstk=np.hstack((arr1,arr2,arr3,arr4))
print(hstk.shape)
print(hstk)

(2, 12)
[[ 2  3  5 22 33 54 22 34 53 25 38 57]
 [ 5  6  7 15 26 37 33 64 75 56 65 73]]


- stack

In [44]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([[22,34,53],[33,64,75]])
arr4=np.array([[25,38,57],[56,65,73]])

hstk=np.stack((arr1,arr2,arr3,arr4),axis=1)
print(hstk.shape)
print(hstk)

(2, 4, 3)
[[[ 2  3  5]
  [22 33 54]
  [22 34 53]
  [25 38 57]]

 [[ 5  6  7]
  [15 26 37]
  [33 64 75]
  [56 65 73]]]


In [24]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([[22,34,53],[33,64,75]])
arr4=np.array([[25,38,57],[56,65,73]])

vstk=np.stack((arr1,arr2,arr3,arr4))
print(vstk.shape)
print(vstk)

(4, 2, 3)
[[[ 2  3  5]
  [ 5  6  7]]

 [[22 33 54]
  [15 26 37]]

 [[22 34 53]
  [33 64 75]]

 [[25 38 57]
  [56 65 73]]]


In [48]:
print(268/6)
print(2000/44.66)

44.666666666666664
44.78280340349306


# Broadcasting arrays for simple calculations

- Arithmetic

In [18]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([22,33,54])
arr4=np.array([[[25,38,57],[56,65,73]],[[258,388,597],[56,65,73]]])
#addition
print(arr1+arr2)
print("-"*20)
print(arr1+arr3)
print("-"*20)
print(arr4+arr1)
print("-"*20)
print(arr1+arr4)
## do the same for all other operations


[[24 36 59]
 [20 32 44]]
--------------------
[[24 36 59]
 [27 39 61]]
--------------------
[[[ 27  41  62]
  [ 61  71  80]]

 [[260 391 602]
  [ 61  71  80]]]
--------------------
[[[ 27  41  62]
  [ 61  71  80]]

 [[260 391 602]
  [ 61  71  80]]]


- comparison


In [26]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])
arr3=np.array([22,33,54])
arr4=np.array([[[25,38,57],[56,65,73]],[[258,388,597],[56,65,73]]])
print(arr1>arr2)
print('-'*20)
print(arr1>arr3)
print('-'*20)
print(arr1<arr4)
print('-'*20)
a=arr1[arr1<arr3]
print(a)

[[False False False]
 [False False False]]
--------------------
[[False False False]
 [False False False]]
--------------------
[[[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
--------------------
[2 3 5 5 6 7]


- Logical


In [41]:
arr1=np.array([[2,3,5],[5,6,7]])
arr2=np.array([[22,33,54],[15,26,37]])

print(arr1 & arr2)
print(np.bitwise_and(arr1,arr2))
print('-'*20)
print(arr1 | arr2)
print(np.bitwise_or(arr1,arr2))
print('-'*20)
print(arr1 ^ arr2)
print(np.bitwise_xor(arr1,arr2))
print('-'*20)
print(~arr2)
print(np.bitwise_not(arr2))
print('-'*20)
print(np.right_shift(arr1,1))
print(np.right_shift(arr1,arr2)) 
print(arr1>>1) 
print('-'*20)
print(np.left_shift(arr1,5)) 
print(np.left_shift(arr1,arr2)) 
print(arr1<<5) 

[[2 1 4]
 [5 2 5]]
[[2 1 4]
 [5 2 5]]
--------------------
[[22 35 55]
 [15 30 39]]
[[22 35 55]
 [15 30 39]]
--------------------
[[20 34 51]
 [10 28 34]]
[[20 34 51]
 [10 28 34]]
--------------------
[[-23 -34 -55]
 [-16 -27 -38]]
[[-23 -34 -55]
 [-16 -27 -38]]
--------------------
[[1 1 2]
 [2 3 3]]
[[0 0 0]
 [0 0 0]]
[[1 1 2]
 [2 3 3]]
--------------------
[[ 64  96 160]
 [160 192 224]]
[[  8388608         0         0]
 [   163840 402653184         0]]
[[ 64  96 160]
 [160 192 224]]


# where clause in arrays

In [43]:
# 1 d array

arr=np.random.randint(1,11,size=10)

index=np.where(arr>=5)
print(index)
print('-'*20)
arr=np.random.randint(1,11,size=(3,3))

index=np.where(arr>5)
print(index)
print('-'*20)
arr=np.random.randint(1,11,size=(3,3,3))

index=np.where(arr>5)
print(index)
print('-'*20)

(array([0, 1, 2, 4, 7, 9], dtype=int64),)
--------------------
(array([0, 1, 2, 2], dtype=int64), array([1, 0, 0, 2], dtype=int64))
--------------------
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64), array([0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1], dtype=int64))
--------------------
