In [2]:
import numpy as np

In [5]:
array=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(array)
print("array[0]")
print(array[0])
print("array[0][1]")
print(array[0][1])
print(array[0,1])
print("array[0][1][1]")
print(array[0][1][1])
print(array[0,1,1])




[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
array[0]
[[1 2 3]
 [4 5 6]]
array[0][1]
[4 5 6]
[4 5 6]
array[0][1][1]
5
5


#### Row access

In [9]:
array=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

print(array[0,:])
print(array[1,0,:])

[[1 2 3]
 [4 5 6]]
[10 20 30]


#### column access

In [15]:
array=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],[[100,200,300],[400,500,600],[700,800,900]]])

print(array[:,1,:])
print("*"*30)
print(array[:,:,2])
print("*"*30)
print(array[:,1,2])

[[  4   5   6]
 [ 40  50  60]
 [400 500 600]]
******************************
[[  3   6   9]
 [ 30  60  90]
 [300 600 900]]
******************************
[  6  60 600]


#### Accessing with specific case

In [31]:
array=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],[[100,200,300],[400,500,600],[700,800,900]]])

print(array[[0,1],:,:])
print("*"*30)
print(array[[0,1],[1,2],:])
print("*"*30)
print(array[[0,1],[1,2],[2,1]])
print("*"*30)
print(array[[0,1],:,[2,1]])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
******************************
[[ 4  5  6]
 [70 80 90]]
******************************
[ 6 80]
******************************
[[ 3  6  9]
 [20 50 80]]


#### Accessing with specific condition

In [39]:
array=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],[[100,200,300],[400,500,600],[700,800,900]]])

print(array>6)
print(array[array>5])
array[array<5]=0
print(array)

[[[False False False]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[  6   7   8   9  10  20  30  40  50  60  70  80  90 100 200 300 400 500
 600 700 800 900]
[[[  0   0   0]
  [  0   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]
