## Reading Data From files

1. txt file

In [3]:
import numpy as np
data=np.loadtxt('data.txt',delimiter="&")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


2. csv file

In [5]:
data=np.loadtxt('data.csv',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


3. npy

In [6]:
data=np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


4. yaml

In [7]:
data=np.loadtxt('data.yaml',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


5. json

In [17]:
data=np.loadtxt('data.json',delimiter=',')
print(data)

[[4. 5. 6.]
 [1. 2. 3.]]
